### ISSUE TITLE
Arrays over 999,999 samples in length throwing errors

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#107]
`_main.pd in "subpatch/_main.pd" @ (x:0, y:22): invalid literal for int() with base 10: '1e+06'`

![screenshot 2016-07-19 20 50 41](https://cloud.githubusercontent.com/assets/294772/16964285/7cfec492-4df2-11e6-9176-92e9681fc489.png)

**Comment by mhroth** [comment]
@ylevtov This issue has now been fixed and pushed to the `dev` channel.

In the future, I **strongly** recommend that you avoid using Pd arrays in favor of tables unless you specifically want to store data in the patch. In other words, when we find `array` we have to store _all_ of your values in the patch. With `table` we only have to store the number of values. The latter is a _lot_ easier on us.

Thanks for your help!

**Comment by ylevtov** [comment]
Great - thanks! Yes, my use of arrays was left over from when I was storing sample data in the patch. Now that we’re no longer doing that I can go back to using tables.

**Comment by mhroth** [comment]
I did also update the table parser, so you're more than welcome to create tables with sizes larger than `1e6` now as well ;)

...@ylevtov, always pushing those boundaries...
