### ISSUE TITLE
Inconsistent [tabwrite] behaviour across JS and Unity builds

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#109]
Test patch:
https://enzienaudio.com/h/yuli/test/o6L4c

![screenshot 2016-07-21 16 55 17](https://cloud.githubusercontent.com/assets/294772/17029646/f0276858-4f63-11e6-9576-b8cef4aecc12.png)

This works perfectly on JS, but when running via Unity on OS X, the `[tabwrite~]` doesn't seem to do anything. The table never gets overwritten.

**Comment by mhroth** [comment]
Thanks @ylevtov. Would you please make the original patch available to us for testing?

**Comment by mhroth** [comment]
A short-term solution would be to use the message `[start 0<`. A better solution will follow.

**Comment by mhroth** [comment]
This issue has now been fixed in the `dev` channel.
