### ISSUE TITLE
Wwise: A maximum of two parameters are only ever shown in the plugin preview area

### ISSUE THREAD

**Issue by knobKompressor** [enzienaudio/heavy#122]
Hello,
I am having a weird issue with specifically Wwise plugins. As you can see from the picture attached, there are three parameters however only 2 are visible for any changes. This happens with other plugins as well. I have exported this as a unity plugin and all of the parameters are available to modify. Would you be able to help me with this? i have also attached the PD script below

Thanks!
# N canvas 729 233 834 681 10;
# X obj 128 450 dac~;
# X obj 110 35 noise~;
# X obj 109 191 phasor~ 600;
# X obj 107 286 *~;
# X obj 540 350 hsl 128 15 0 1 0 0 empty empty Volume -2 -8 0 10 -262144

-1 -1 12700 1;
# X obj 110 157 +~;
# X obj 110 112 +~ 600;
# X obj 278 172 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144

-1 -1;
# X obj 278 238 line~;
# X msg 323 211 0 500;
# X obj 105 375 *~;
# X msg 278 211 1 800;
# X obj 202 35 noise~;
# X obj 201 191 phasor~ 600;
# X obj 199 286 *~;
# X obj 202 157 +~;
# X obj 202 112 +~ 600;
# X obj 204 367 *~;
# X obj 106 313 bp~ 9000 15;
# X obj 199 313 bp~ 9000 15;
# X obj 110 66 lop~ 0.3;
# X obj 323 187 del 800;
# X obj 375 170 bng 15 250 50 0 empty empty empty 17 7 0 10 -262144

-1 -1;
# X obj 375 236 line~;
# X msg 420 209 0 500;
# X msg 375 209 1 800;
# X obj 420 185 del 800;
# X obj 202 66 lop~ 0.5;
# X obj 202 90 *~ 8000;
# X obj 110 90 *~ 9000;
# X obj 469 133 random 1000;
# X obj 471 76 tgl 15 0 empty empty empty 17 7 0 10 -262144 -1 -1 1

1;
# X obj 305 119 random 10;
# X obj 305 143 sel 0 5;
# X obj 579 30 r mosq_on @hv_param 0 1 1;
# X obj 580 89 r mosq_vol @hv_param 0 1 1;
# X obj 376 19 loadbang;
# X floatatom 506 166 5 0 0 0 - - -;
# X obj 469 104 metro 1200;
# X obj 578 60 r mosq_speed @hv_param 100 2000 1200;
# X connect 1 0 20 0;
# X connect 2 0 3 0;
# X connect 3 0 18 0;
# X connect 4 0 10 1;
# X connect 4 0 17 1;
# X connect 5 0 2 0;
# X connect 6 0 5 0;
# X connect 7 0 11 0;
# X connect 7 0 21 0;
# X connect 8 0 3 1;
# X connect 9 0 8 0;
# X connect 10 0 0 0;
# X connect 11 0 8 0;
# X connect 12 0 27 0;
# X connect 13 0 14 0;
# X connect 14 0 19 0;
# X connect 15 0 13 0;
# X connect 16 0 15 0;
# X connect 17 0 0 1;
# X connect 18 0 10 0;
# X connect 19 0 17 0;
# X connect 20 0 29 0;
# X connect 21 0 9 0;
# X connect 22 0 25 0;
# X connect 22 0 26 0;
# X connect 23 0 14 1;
# X connect 24 0 23 0;
# X connect 25 0 23 0;
# X connect 26 0 24 0;
# X connect 27 0 28 0;
# X connect 28 0 16 0;
# X connect 29 0 6 0;
# X connect 30 0 26 1;
# X connect 30 0 21 1;
# X connect 31 0 38 0;
# X connect 32 0 33 0;
# X connect 32 0 37 0;
# X connect 33 0 7 0;
# X connect 33 1 22 0;
# X connect 34 0 31 0;
# X connect 35 0 4 0;
# X connect 36 0 31 0;
# X connect 38 0 30 0;
# X connect 38 0 32 0;
# X connect 39 0 38 1;

<img width="936" alt="screen shot 2016-08-15 at 13 45 32" src="https://cloud.githubusercontent.com/assets/21038064/17664820/a03cfd78-62ee-11e6-9ee5-7a72c8757bf6.png">

**Comment by diplojocus** [comment]
@Playrok sorry for the delay, yep you're right this happens. One workaround right now is that you can double click the plugin 'row' and it will show a dedicated window that contains all the parameters.

**Comment by diplojocus** [comment]
![untitled](https://cloud.githubusercontent.com/assets/594588/18745310/9b972dd2-80b9-11e6-8321-39376d42e194.png)

**Comment by diplojocus** [comment]
@Playrok hey I've fixed this issue but have noticed there's some problem where wwise only allows a maximum width in the smaller plugin view. If you have more than 4 parameters then the rest will be cut off, but you can always view them in the larger window. I'm looking into what we can do about that.

**Comment by diplojocus** [comment]
Note: this fix is currently in the dev channel and will likely be included in the next release.

**Comment by diplojocus** [comment]
Just adding some additional info here, Wwise actually only supports a set width in the small plugin view, so I've hardcoded a maximum of 4 parameters to display here.
