### ISSUE TITLE
JS console errors

### ISSUE THREAD

**Issue by fr4nky8oy** [enzienaudio/heavy#135]
Hi guys, I am new with heavy , sorry for the basic question:
My PD patch passes all checks on my account, but it does not play. I have checked the JS console in Chrome, it shows errors that i don't really understand. Could you please help? thanks https://enzienaudio.com/h/fr4nky8oy/VS/

**Comment by fr4nky8oy** [comment]
just tried re-uploading this patch: https://enzienaudio.com/h/jarm/algo_test/

and get the same errors:

![screen shot 2016-10-16 at 18 55 13](https://cloud.githubusercontent.com/assets/12418391/19419568/2ebe34c2-93d2-11e6-81ce-3f62e96fdd0c.png)

**Comment by diplojocus** [comment]
@fr4nky8oy do you still get these errors?

**Comment by fr4nky8oy** [comment]
@diplojocus sorry just saw this :( 
 thats what i asked you on slack yesterday. sorry joe my bad
