### ISSUE TITLE
Setting right inlet of [pipe] to a negative value sets the internal delay in [metro] to 0

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#139]
![screenshot 2016-11-22 17 04 14](https://cloud.githubusercontent.com/assets/294772/20533748/87e10090-b0d6-11e6-943b-9653f912eeb8.png)

https://enzienaudio.com/h/yuli/horizons_mpsf/P0WZa/

**Comment by ylevtov** [comment]
This can be closed, now, right?

**Comment by mhroth** [comment]
Fixed! as of `r2016.11`.
