### ISSUE TITLE
int HeavyContextInterface::getParameterInfo(int index, HvParameterInfo *info) always returns 0

### ISSUE THREAD

**Issue by ragnaringi** [enzienaudio/heavy#145]
The header documentation states:

> * If info is null then the total number of parameters is returned.
> * If info is not null, then the structure is filled in for the given parameter index.

However, the implementation always returns zero:

```
if (info == nullptr) {
    return 0;
 }
```

**Comment by mhroth** [comment]
This issue is fixed in `r2016.11`.
