### ISSUE TITLE
_hv_table_resize not defined in js target

### ISSUE THREAD

**Issue by owenhindley** [enzienaudio/heavy#146]
- I open up the provided html that comes with the downloaded patch
- create a new blank AudioBuffer object `bar`
- call `patch_instance.fillTableWithAudioBuffer(table_name, bar)`

and I get an `patchName_Lib.min.js:1 Uncaught ReferenceError: _hv_table_resize is not defined`

**Comment by diplojocus** [comment]
This has been fixed in `2016.11`
