### ISSUE TITLE
List of Unity generators wrong in uploader.py

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#155]
Not sure about the others but for Unity, there shouldn't be a plain `unity-macos` one, right? (only `unity-macos-x86` and `unity-macos-x64`?)

Also in the usage message, there is a plain `unity` given as an example generator, which is also doesn't exist as a generator?

**Comment by mhroth** [comment]
@ylevtov Thanks for this. `unity-macos-x86` and `unity-macos-x64` are definitely correct. There is no longer a simple `unity-macos`; we no longer generate universal binaries.

I'll double-check the documentation.
