### ISSUE TITLE
[inlet] -> [f $1] together with [loadbang] not producing expected behaviour

### ISSUE THREAD

**Issue by krighxz** [enzienaudio/heavy#170]
Using loadbang to initialise an [f $1] object doesn't work when an inlet (with no incoming data) is also connected to [f].
[k.ramp.pd.txt](https://github.com/enzienaudio/heavy/files/778214/k.ramp.pd.txt)

**Comment by mhroth** [comment]
@krighxz would you please describe what is the expected behavior in this patch? This patch looks like it's meant to be an abstraction fitting into something else, based on the dollar args. As it is, `[f $1]` outputs 0 after the loadbang, as expected.

**Comment by diplojocus** [comment]
@krighxz any news on this? I've never noticed this behaviour before and have used that idiom quite extensively.
