### ISSUE TITLE
Setting random seed via unity doesn't seem to work

### ISSUE THREAD

**Issue by atellio** [enzienaudio/heavy#173]
I have the following setup (with unity sending a random seed from between 0 and 9999):

`[r seedFromUnity @hv_param 0 9999 1]`
  |
`[seed $1<`
  |
`[Random 5]`

With a print object I've been able to confirm that the seed message is being set to a different value each time, but output from random is always the same sequence nevertheless. 

Additionally, not 100% certain about this but it appears as if the `[seed $1<` message is triggering the `[Random]` object to send output, which shouldn't be the case

Any ideas what I might be doing wrong?

**Comment by mhroth** [comment]
Thanks @atellio, that's a bug on our side. I've update the `dev` channel with a fix for this.
