### ISSUE TITLE
Reloading a sample simply

### ISSUE THREAD

**Issue by diemildefreude** [enzienaudio/heavy#188]
This time-freeze abstraction I'm trying to import requires a shortening of the sample via this [resize( construction pictured below. In PD, I play the file into the [tabwrite~] using [readsf~] at the same time as I input the array size and execute the [resize( command. This is probably not the best way to do it, but it does afford me the flexibility of trying different array sizes with the same sample.

The problem in Unity is that [resize( clears the array whenever it's input into the array and I need a way to reload the sample. I can see two possibilities:

1) Load the sample into one array via Unity, and then playback that sample into a second array using the [t b b] / [resize( construct as is. (This should work, but it seems like it should be unnecessary to have two arrays for the same thing.)

2) Determine the array size I want ahead of time and remove [resize(. (This would be simpler, but it would remove some flexibility from my work process as I'd have to recut samples manually more often)

![zerozeroload](https://cloud.githubusercontent.com/assets/16056630/24353394/4df5ac00-1328-11e7-84d4-917387d0e5ff.png)

If there's a simpler way to approach this, please let me know.

**Comment by diplojocus** [comment]
Hi @diemildefreude hate to break it to you but for starters this will never work in heavy because `[readsf~]` isn't supported and you can't send a `[resize $1(` message to a table. That Pd feature isn't implemented.

I don't know if I understand the eventual goal fully but it's worthing noting that when loading an audio clip from Unity into heavy, the table will be resized accordingly.

Also you could create a table of a maximum size, and then else where in your patch store the currently loaded sample length.

**Comment by diemildefreude** [comment]
@diplojocus Ah, good thing you told me about [resize( . So you mean load the whole file into the array and then use the shortened length to only read it upto a certain point, right?

**Comment by diplojocus** [comment]
Sure that also works :)

**Comment by diemildefreude** [comment]
So to do that, I should divide the max array size by the desired array size and then multiply the output of [phasor~] by that, right? I didn't make this patch though, so I'm not really sure.

![zerozeroload2](https://cloud.githubusercontent.com/assets/16056630/24354955/f5693b04-132e-11e7-8508-bc1515a5cef8.png)

**Comment by diplojocus** [comment]
Is it important to calculate zero crossings? Can you apply some kind of window to your grains (I'm guessing you're doing some kind of grain-based table reading).

**Comment by diemildefreude** [comment]
Finding the zero-crossings helps to make reading smooth for the time-stretch. The person who made it wrote:

"it will write any incoming sound to an array of a given size, then search for the first and the last zerocrossing and playback this section. so its basically wavestealing, freezing..
the size of the array to record to would be around 200-500 samps for 2 - 3 periods normal pitch sound at 44100 samplerate..."

I can pass your question along to him, but I really don't get exactly how it works myself.

**Comment by diplojocus** [comment]
Where did you get the patch from? Is there an explanation to algorithm with it?

**Comment by diemildefreude** [comment]
by going around the internet and begging people for help, like I do with you: http://forum.pdpatchrepo.info/topic/9909/time-stretching-patches-any-recommendations/11

I'll ask him about it though. In the meantime, I guess I'll opt for option 2)

**Comment by diplojocus** [comment]
I can understand why you'll want to detect zero-crossings, but as heavy only supports a subset of Pd's functionality you do have to be careful with the approach you take. Some techniques might work in pd but not in heavy for example.

**Comment by diemildefreude** [comment]
Yes, I imagine that's the source of my other issue, though I'm not sure if I've pinpointed the problem there: https://github.com/enzienaudio/heavy/issues/178

Heavy is really like learning a new language, since you end up solving things so differently than you would in PD. If you know any heavy-compatible time-stretching abstractions, I'd be happy to try them out. x) In the meantime, I'll try precutting the sample and seeing if it works like that.

**Comment by diplojocus** [comment]
Have you looked at the G09.pitchshift.pd example in the Pd browser menu? You should be able to use a variant of that to achieve some kind of freezing effect.

**Comment by diemildefreude** [comment]
You know, I'm not 100% sure at the moment, but I looked at a LOT of time-stretching patches a while back and I think some of them were based on that principle but tended not to sound too good. I'll give them another shot if need be.

**Comment by diplojocus** [comment]
If you increase the number of overlapped grains you'll get a smoother sound. But yeah it's a fairly primitive technique, but can work pretty well in some situations.

**Comment by diemildefreude** [comment]
I think the issue was the resemblance to the original sound.

**Comment by diemildefreude** [comment]
I'm going to try using the PD version of this patch to export .wavs of the right sample length. If I can do that and bypass the resizing, maybe it'll work. But first I think I'm going to eat something. Thanks for your time, @diplojocus .
