### ISSUE TITLE
Awake VS Start when Sample-Loading in an Instantiation (Solved?)

### ISSUE THREAD

**Issue by diemildefreude** [enzienaudio/heavy#190]
I made this patch/plugin that takes two audio samples. One is a regular guitar string pluck, the other is a smaller cut of the same file. The patch transitions from the former into a time-stretch based on the latter. The plugin works if I have it in the heirarchy already before starting. However, if I save the Game Object, which has the plugin script, the sample loader script and Audio Source attached to it, as a Prefab and try to instantiate this Game Object during runtime, the initial pluck is missing and it sounds like a smooth fade-in of the time-stretch sound. Below is a Unity package. Please import it and open the "soundtest" scene. You'll find a 'SoundTest' object in the heirarchy and an 'InstantiateSound' object as well. 

github is again not letting me upload the zipped package, so here's a tinyurl link:  http://s000.tinyupload.com/?file_id=40573428668419922314

A few more details: the patch is setup with a 1-second delay before the pluck should be heard. This is indicated by the 'loadbang' and 'delayedloadbang' messages in the console.

**Comment by diemildefreude** [comment]
Some further testing with a print object after the array size showed that, when instantiating the object, the array size was showing up as 0. Now this value is derived from a separate SampleLoader script on the same object, which then sends the array size to the plugin-script. Putting the SampleLoader's code in Awake() instead of Start() fixes this - **but only when instantiating the object.** Having the SampleLoader's code in Awake() and pressing Play when the GameObject is already in the scene leads to a NullReferenceException error. So something about initalizing the GameObject seems to affect the order of script initialization.  

SampleLoader script:

```
using UnityEngine;
using System.Collections;

public class SampleLoader : MonoBehaviour
{

  public AudioClip _clip;
  public AudioClip _clip2;
  private Hv_sustainplayertest_AudioLib _audio;


	// Use this for initialization
	void Awake ()
    {
        _audio = GetComponent<Hv_sustainplayertest_AudioLib>();
        _audio.samples = (float)_clip.samples;
        _audio.FillTableWithMonoAudioClip("3-buffer", _clip);

        _audio.FillTableWithMonoAudioClip("3-section", _clip2);
	}
```

**Comment by diemildefreude** [comment]
OK, for the sake of my instantiation process, I've combined the set-parameter script (https://github.com/enzienaudio/heavy/issues/191) with the sample-loader while also having it instantiate the heavy-script. The result works both as an instantiated prefab and when already in the scene at Play:

```
using UnityEngine;
using System.Collections;

public class SampleLoader : MonoBehaviour
{

    public AudioClip _clip;
    public AudioClip _clip2;
    public float glissando_toggle;
    public float mix;
    public float readeronoff;
    public float start_delay;
    public float transpose;

    private Hv_sustainplayertest_AudioLib _audio;


	// Use this for initialization
	void Awake ()
    {
        AddSound();        
	}

	public void AddSound()
    {
        print("add sound");
        _audio = gameObject.AddComponent<Hv_sustainplayertest_AudioLib>();
        _audio.samples = (float)_clip.samples;
        _audio.FillTableWithMonoAudioClip("3-buffer", _clip);
        _audio.FillTableWithMonoAudioClip("3-section", _clip2);
        _audio.mix = mix;
        _audio.readeronoff = readeronoff;
        _audio.start_delay = start_delay;
        _audio.transpose = transpose;
    }


}
```

**Comment by diplojocus** [comment]
Hi @diemildefreude the AudioLib's dll get's loaded in Unity's `Awake()` callback, so to be sure you should load your samples in the `Start()` callback.

As for the issues with Prefabs, I'm not at my windows machine atm so I can't test your project, but there shouldn't be any issue instantiating the plugin at runtime. Are you sure that you're loading the samples correctly after constructing your prefab?

**Comment by diemildefreude** [comment]
@diplojocus Yes, it works just as well if I use the above script in Start() instead of Awake() (though this doesn't fix the problems mentioned in https://github.com/enzienaudio/heavy/issues/194 ) The previous difficulty was probably caused by having too many separate scripts whose order of execution messed things up. Though
