### ISSUE TITLE
Unity Parameters Not Updating During Play mode

### ISSUE THREAD

**Issue by bsangston** [enzienaudio/heavy#195]
I'm building a fairly complex generative music system for a game that I'm working on, and I'm running into some strange behavior with the way that plugin values are updated during play mode. 

The system I am building needs to respond to game state data in order to update the patch in realtime, but that doesn't actually seem to be happening consistently. I can update parameters as expected when modifying things directly in the editor (both in and out of play mode), but when modifying the actual parameters in a script, the changes don't take affect in my Pd patch, even though the parameter value is being updated in the editor. For example, there is a "Mode" parameter that determines the current mode the music is being generated in. These are mapped to float values 1 - 7. I am able to successfully change the mode manually in the editor during play mode, but when my script changes the value, the editor is updated, and the actual change doesn't take effect in the Pd patch. 

<img width="572" alt="screen shot 2017-04-08 at 1 27 40 am" src="https://cloud.githubusercontent.com/assets/14152958/24826017/95dc65b0-1bfa-11e7-8d8a-931abe5e6552.png">

The only difference is literally me clicking and dragging the sliders on the GUI vs modifying the values via scripts. 

hv_events seem to work just fine, it's only any issue with hv_parameters. 

Has anyone experienced an issue like this and know what might be causing it? I've been hopelessly struggling with this for a while now, so any help would be greatly appreciated.

**Comment by bsangston** [comment]
Unbelievable. Just learned there was a SetFloatParameter() method haha. I thought the parameters were supposed to be directly assigned! 

That did the job.

**Comment by diplojocus** [comment]
Ahh sorry @Bsangston yes you should use `SetFloatParameter()` and not set the public float variable directly (it will only update the UI).

**Comment by mhroth** [comment]
@Bsangston `SetFloatParameter` is described in detail in our [Unity documentation](https://enzienaudio.com/docs/index.html#06.unity#exposing-and-setting-parameters). What could we have done to make this functionality more clear?

**Comment by bsangston** [comment]
My issue was largely due to my own ignorance, _but_ I would hardly describe `SetFloatParameter` as being described "in detail." As far as I've seen the only mention of it is an example code block on the Unity documentation page, which I must've just missed when learning how to use Heavy with Unity.

If you're concerned about making the documentation more clear, I don't think it would hurt to have a small explanation of accessing the value directly vs. `SetFloatParameter` and `GetFloatParameter`. 
Frankly I actually still don't know the difference between `GetFloatParameter` and accessing the parameter value directly (or if there even is one)

Or, it might make more sense just to have the fields private if modifying them directly only affects the editor, or throw some warning about them being read-only. I assumed I was modifying the values correctly because I could see them change in realtime, even though they had no effect (which led me to believe something much more complicated was going on).

Again, I should have been able to figure this out long before I did (especially considering it's the same for `hv_event`), but those are just some suggestions.
