### ISSUE TITLE
How to load sample into a PD table via Wwise?

### ISSUE THREAD

**Issue by abarnacle** [enzienaudio/heavy#236]
Could someone please explain how to load a sample via Wwise into a table in a PD-via-Heavy Wwise source? I've tried several @hv_  prompts in the PD patch as shown in the photo but none worked or I could not work out how to access the table from within Wwise...

<img width="237" alt="screen shot 2017-11-14 at 10 59 33" src="https://user-images.githubusercontent.com/33655808/32776709-51d28906-c92b-11e7-8780-2e55fa9ba6c5.png">

**Comment by diplojocus** [comment]
Hi @abarnacle sorry for the massive delay! I must have missed this. 

You can do `[table startGate 0 @hv_table]` the `@hv_table` annotation will create an interface button the Wwise plugin UI for loading wave files to the table.
