### ISSUE TITLE
Windows VST2 build down?

### ISSUE THREAD

**Issue by s9lucas** [enzienaudio/heavy#238]
I'm getting 404 errors when trying to request VST2 Win32 or 64 builds. I've verified it not something with my patch because I tried re-uploading a known working patch and get the same problem.

I'll set up to do builds on my end but I was using VST2 for fast testing so I lose some of that benefit if it requires compiling.

Thanks,
-Stephen

**Comment by s9lucas** [comment]
The problem seems to have been resolved recently. I'm assuming it was corrected on the server since I have  patches where nothing changed on my end.

Thanks,
-Stephen

**Comment by diplojocus** [comment]
Hi @s9lucas apologies about that, the VST windows builder has indeed been fixed recently.
