### ISSUE TITLE
Can't Get Patch to Upload, But Objects Are Supported

### ISSUE THREAD

**Issue by sergiogranadamoreno** [enzienaudio/heavy#241]
[se_version1.zip](https://github.com/enzienaudio/heavy/files/1686870/se_version1.zip)

I'm having problems uploading the attached patch.

I'm not certain what the issue is since I did upload a similar version of this patch a year ago:

[https://enzienaudio.com/h/sergiogranadamoreno/test5/](https://enzienaudio.com/h/sergiogranadamoreno/test5/)

error message: "We failed to process the uploaded patch. Verify that you are only using supported objects, who you can see listed on the PD Objects page."

**Comment by diplojocus** [comment]
Hi @sergiogranadamoreno it looks like its could because of a '.' in one of your parameter names? Try using just alphanumerical characters. 

Seems your patch is getting past our parser. I'll take a look

**Comment by sergiogranadamoreno** [comment]
Yes! You are certainly right. I changed all the parameter names containing '.' and now I'm able to upload the patch. Many thanks!
