### ISSUE TITLE
404 error for downloading patches and preview

### ISSUE THREAD

**Issue by RobertoHuge** [enzienaudio/heavy#244]
Hi,

I'm trying to upload patches and all of the links (including preview) are providing 404 errors apart from the source pd and C/C++ links. I tested with a patch that I had uploaded and converted successfully last week, and it returned the same problem.

https://enzienaudio.com/h/RobertoHuge/

**Comment by diplojocus** [comment]
hi @RobertoHuge sorry about that just had a small server hiccup, should be working now

**Comment by RobertoHuge** [comment]
Yeah it's all working now - thank you very much!
