### ISSUE TITLE
We failed to process the uploaded patch. Verify that you are only using supported objects

### ISSUE THREAD

**Issue by matt299** [enzienaudio/heavy#258]
I get the error message 'We failed to process the uploaded patch. Verify that you are only using supported objects, who you can see listed on the PD Objects page.'
I don't know why this is.
I believe my patch only contains supported objects and is under 1MB
Please help.

[stuff.zip](https://github.com/enzienaudio/heavy/files/1907245/stuff.zip)

**Comment by diplojocus** [comment]
hey @matt299 nice find, that's a pretty subtle bug! 

In your `eeriewindatmos` patch remove the `^` from the `Vocal Formants ^` comment. It should work then.

**Comment by matt299** [comment]
Hi @diplojocus Still no luck :/ I have removed all instances of ^, <, > and : and still it doesn't work 

[stuff.zip](https://github.com/enzienaudio/heavy/files/1908733/stuff.zip)

**Comment by diplojocus** [comment]
hi @matt299 in `_main > eeriewindatmos > windSource > sendsandreceivers` there's a send object `[s ^]`. I think there's another one somewhere else, but I can't find it, maybe the receive to that send?

Are you on Windows by any chance?

**Comment by matt299** [comment]
Hi @diplojocus thank you for your assistance, I appreciate it. I have since changed all sends and receives to have standard characters, with the exception of `/` and it's still not working.
I am on Mac.
[stuff.zip](https://github.com/enzienaudio/heavy/files/1919163/stuff.zip)

**Comment by diplojocus** [comment]
Woah, how did you manage to type that character? Would you be able to send a patch with just the `^` in a comment created on your machine? It looks like an text encoding issue.

**Comment by matt299** [comment]
I quickly made this to see if the characters were causing an issue, but this works when I go to upload![stuff test.zip](https://github.com/enzienaudio/heavy/files/1919195/stuff.test.zip)

**Comment by diplojocus** [comment]
ok so you've fixed it?

**Comment by diplojocus** [comment]
I'm interested in how you're generating those characters on a mac that end up borking the compiler. Do you have a non-english language set? What macos and Pd version are you using?

**Comment by matt299** [comment]
I haven't managed to fix it. I'm just troubleshooting. I don't think it's the characters that are causing the issue because a simple patch with weird characters compiles, but my patch isn't.
I'm using a normal language set, Pd-0.48.0 and am on the most up to date version of macos.

**Comment by diplojocus** [comment]
@matt299 there were some hidden `[receive]` objects with `^` in the WindFormats subpatch, had to scroll up to see them. Your patch compiles for me here: https://enzienaudio.com/h/diplojocus/stuff/ though I haven't tested it beyond that.

Would you mind still send me a patch with just a `^` in it?

**Comment by matt299** [comment]
ahhhhh yes!
That's it. Thank you so much, I didn't spot that!
It compiles 👍

**Comment by diplojocus** [comment]
Awesome, yeah if I write `^` in the pd patch it compiles for me, so I'm not sure what is different on your end!
