### ISSUE TITLE
Unity script without error but not emitting sound

### ISSUE THREAD

**Issue by warpcut** [enzienaudio/heavy#262]
Hi, i've tryed to use heavy initialy on wwise.
My patch was working but when an event was calling it from unity it was releasing an error "No authorization".
So i decided to try with the unity plugin, this time the plug-in is loaded without any problem.
After adding it to my object btw i recived a message that was sayng that there were no audio listnere on the scene.
Actually i have two of them beacause i'm using them with wwise and they are working perfectly.
The problem is that the plug-in is not emitting any sound.

These are the message and the script-impoted component.
![message](https://user-images.githubusercontent.com/17721684/40742045-8ba79140-644d-11e8-9d44-bf54d6f395b5.PNG)
![script-added](https://user-images.githubusercontent.com/17721684/40742052-919fc1b2-644d-11e8-9936-852133071519.PNG)

**Comment by diplojocus** [comment]
@warpcut I think this might be a conflict with using both Wwise and the native unity audio system at the same time. Doesn't Wwise enable the `Disable Audio Engine` option in the preferences by default? Can you create a test Unity project without Wwise integrated and see if you get the same result with the Unity plugin?

**Comment by diplojocus** [comment]
> My patch was working but when an event was calling it from unity it was releasing an error "No authorization".

Can you provide more information on this? Heavy generated Wwise plugins should be working fine in Unity.

**Comment by warpcut** [comment]
Thanks for the fast replay.
Basically if i download the wwise x Windows 64, there are 5 files inside.
The doc says ti take the teoria auth and Place Them in plugin folder.
After doing this i cani sera the plugin in wwise. I cani add Them to a sound fx, and if i Press play It works, i cani hear the sound.
But when i go back ti unity It give me andrebbe error. Like "plugin notte registered" or something like that.

**Comment by diplojocus** [comment]
`Plugin Not Registered` could mean that the runtime plugin hasn't been installed into the Unity project. Have you installed it via the instructions found here: https://enzienaudio.com/docs/index.html#07.wwise#unity-integration

**Comment by warpcut** [comment]
Ok, i definitely had something wrong with my project, i started a new one reimported everything and now, in the new one, it works.
Thanks for the help!
