### ISSUE TITLE
Replacing a sound in Unity that uses PlayClipAtPoint() rather than GetComponent<AudioSource>().Play()?

### ISSUE THREAD

**Issue by TomAnks** [enzienaudio/heavy#264]
I'm currently trying to replace all of the audio FX in the free [Unity 2D Platformer Demo](https://assetstore.unity.com/packages/essentials/tutorial-projects/2d-platformer-11228) with procedural audio using Pure Data and Heavy.

I've had no problem replacing the bazooka sound using the code below:

```
                Hv_Bazooka_AudioLib script = GetComponent<Hv_Bazooka_AudioLib>();	
	
		script.SetFloatParameter(Hv_Bazooka_AudioLib.Parameter.Blastvolume, 0.35f);
		script.SetFloatParameter(Hv_Bazooka_AudioLib.Parameter.Blastdecay, 0.1f);
		script.SetFloatParameter(Hv_Bazooka_AudioLib.Parameter.Blastspread, 0.1f);

		// If the fire button is pressed...
		if(Input.GetButtonDown("Fire1"))
		{
			
			// ... set the animator Shoot trigger parameter and play the audioclip.
			anim.SetTrigger("Shoot");
			GetComponent<AudioSource>().Play();

			//Send Bang to pd script
			script.SendEvent(Hv_Bazooka_AudioLib.Event.Bang);
```

But now I'm trying to replace the bomb explosion sound (when you detonate a bomb or hit the bomb crate with a missile) and it's not as straightforward. I'm having 2 main issues:

1) The bomb object itself only appears in the Unity hierarchy when the explosion occurs, whereas the 'gun' object I used to implement the bazooka sound is always available. This means I can't drag my Heavy script into the inspector. If I attempt to do this by pausing the game when the object appears, the script disappears when I restart the game

2) If I try and do something similar to what I did with the bazooka sound in the Explode() method in the original code, the bomb doesn't actually explode and also makes no sound. For now I've set the PlayClipAtPoint volume to 0, because deleting it also caused the explosion not to work.

	
```
public void Explode()
	{
		
		// The player is now free to lay bombs when he has them.
		layBombs.bombLaid = false;

		// Make the pickup spawner start to deliver a new pickup.
		pickupSpawner.StartCoroutine(pickupSpawner.DeliverPickup());

		// Find all the colliders on the Enemies layer within the bombRadius.
		Collider2D[] enemies = Physics2D.OverlapCircleAll(transform.position, bombRadius, 1 << LayerMask.NameToLayer("Enemies"));

		// For each collider...
		foreach(Collider2D en in enemies)
		{
			// Check if it has a rigidbody (since there is only one per enemy, on the parent).
			Rigidbody2D rb = en.GetComponent<Rigidbody2D>();
			if(rb != null && rb.tag == "Enemy")
			{
				// Find the Enemy script and set the enemy's health to zero.
				rb.gameObject.GetComponent<Enemy>().HP = 0;

				// Find a vector from the bomb to the enemy.
				Vector3 deltaPos = rb.transform.position - transform.position;

				// Apply a force in this direction with a magnitude of bombForce.
				Vector3 force = deltaPos.normalized * bombForce;
				rb.AddForce(force);
			}
		}

		// Set the explosion effect's position to the bomb's position and play the particle system.
		explosionFX.transform.position = transform.position;
		explosionFX.Play();

		// Instantiate the explosion prefab.
		Instantiate(explosion,transform.position, Quaternion.identity);

		// Original explosion sound effect muted
		AudioSource.PlayClipAtPoint(boom, transform.position, 0.0f);

		//Set 'script' equal to the bigBoom component
		Hv_bigBoom_AudioLib script = GetComponent<Hv_bigBoom_AudioLib>();		

		//Set parameters for bigBoom
		script.SetFloatParameter(Hv_bigBoom_AudioLib.Parameter.Blastvolume, 0.5f);
		script.SetFloatParameter(Hv_bigBoom_AudioLib.Parameter.Blastdecay, 1.0f);
		script.SetFloatParameter(Hv_bigBoom_AudioLib.Parameter.Blastspread, 0.0f);
		script.SetFloatParameter(Hv_bigBoom_AudioLib.Parameter.Firevolume, 0.4f);

		GetComponent<AudioSource>().Play();
		script.SendEvent(Hv_bigBoom_AudioLib.Event.Bang);

		// Destroy the bomb.
		Destroy (gameObject);
	}
```

I'm aware that issue 1) is probably what's causing the failure in issue 2), and it's probably more of a Unity issue than a Heavy issue (trying to add a Heavy script to an object that isn't initially available in the hierarchy), but if anyone can offer any assistance I'd really appreciate it!

**Comment by diplojocus** [comment]
Hi @TomAnks a typical solution to this would be to instantiate the explosion GameObject from a Prefab that already has the Heavy script attached.

See the docs on prefabs [here](https://docs.unity3d.com/Manual/Prefabs.html)  and [here](https://docs.unity3d.com/Manual/InstantiatingPrefabs.html)

Your instantiatation sequence might look something like this:
```
public GameObject explosionPrefab;

void Start() {
   GameObject explosion = (GameObject) Instantiate(explosionPrefab, new Vector3(0, 0, 0), Quaternion.identity);
   Hv_explosion_AudioLib script = explosion.GetComponent<Hv_explosion_AudioLib>();
   // do things with the heavy script
}
```

**Comment by TomAnks** [comment]
Hi Joe, thanks for that. I've not used Unity before this so I'm still figuring things out - I'll let you know how I get on!

**Comment by diplojocus** [comment]
No problem, the easiest way to generate the Prefab is to create a gameobject in the heirarchy with all the components you want to use. Then drag it into the Assets/File section and it'll turn into a blue cube. Delete the old gameobject and drag the new prefab back in.

**Comment by TomAnks** [comment]
Creating a prefab and referencing it in the Bomb.cs code worked perfectly, thanks Joe!

**Comment by diplojocus** [comment]
🎉
