### ISSUE TITLE
Any way of converting the patch offline?

### ISSUE THREAD

**Issue by warpcut** [enzienaudio/heavy#267]
Since the website Is down, i would like to ask if there is a way to do the process of convertion offline?

**Comment by diplojocus** [comment]
https://github.com/enzienaudio/hvcc

**Comment by warpcut** [comment]
I closed It because i found the compiler.
Many thanks.

**Comment by warpcut** [comment]
I'm experiencing crashes while pressing play with play "on awake" turned on.
I'm using unity on MacBook pro-2017.
I've seen another issue [#175](https://github.com/enzienaudio/heavy/issues/175#issue-210215995) where the problem was a "loop" in the patch but I actually have no loop in mine.
So what could it be related with? It's a bug experienced only by osx users or also with windows?
