### ISSUE TITLE
Use Heavy Markup in PureData to export specific receivers

### ISSUE THREAD

**Issue by diplojocus** [enzienaudio/heavy#30]
When generating parameters from [receive] objects we should only create code from user specified instances. [receive]/[send] objects are commonly used within a patch architecture and having a global scope for these in the integration interface would be too verbose and potentially confusing. 

Proposal for a Heavy mark-up specification to tag certain [receiver] objects for automatic code generation of parameters. 

i.e. in a patch a user would create an object such as [r @hv_param freq 0 1 0.5], which would generate a parameter to the patch called "freq" with minValue=0, maxValue=1 and defaultValue=0.5

**Comment by ylevtov** [comment]
As this is mainly a debugging feature for the patch preview, it would be nice to not disrupt the usual Pd patching conventions too much.

How about something like
`[r freq @hv_param 0 1 0.5]`

Name is implied from the first argument of the [receive]. And could the defaultValue be optional? It's better to keep the initialisation in the patch, I feel...

**Comment by mhroth** [comment]
Yeah, I'm liking this. @diplojocus?

**Comment by diplojocus** [comment]
Yeah good idea @ylevtov 

Although I don't just see it as a debugging feature, as when it comes to more complicated integration projects it'll be handy to choose which parameters get auto-generated and their respective values/settings

**Comment by diplojocus** [comment]
The default value is mainly to set the UI slider values, plus for example in the Wwise integration there needs to be something to initialise to.

If you use the output in your own code then the default value isn't an issue as it's only relevant to the preview. I don't mind it being optional but it does need a value assigned, potentially the minimum part of the range?

**Comment by ylevtov** [comment]
Yeah sounds good. So the default value is the minimum, unless otherwise specified.

Does that mean that it will send the default value through to Pd when the preview sliders are initialising? Or is the initialisation purely for the benefit of the GUI?
