### ISSUE TITLE
Consider a different system for auto-generation of GUI sliders for patch preview

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#33]
It's a really great feature, but...
some patches e.g. reverbs, have many [receives], only a few of which are actually useful to visualise. 

Could there perhaps be a special string that must be present in the [receive] name in order for Heavy to auto-generate a GUI slider for it? 

e.g. 
[r myParameter] would NOT auto-generate a slider whereas
[r myParameter-GUI] would auto-generate a slider

**Comment by mhroth** [comment]
@diplojocus has been talking about this for a while. See https://github.com/enzienaudio/heavy/issues/30. What about something with annotations, like `[r myParameter @hv_gui]`?

**Comment by ylevtov** [comment]
Duplicate issue - continuing discussion original - #30.

**Comment by mhroth** [comment]
Or maybe `[r myParameter @hv_gui 0 1]` to specify maximum and minimum range.
