### ISSUE TITLE
osc~ playing at the wrong pitch

### ISSUE THREAD

**Issue by re-sounding** [enzienaudio/heavy#37]
Windows 8.1.
Chrome  42.0.2311.90 
Pd 0.46.5

[osc~ 440] in the patch is playing at 478.9Hz in the browser. Possibly a sample rate issue? The ratio is the same as 48000/44100. Windows runs at 48KHz by default.

**Comment by diplojocus** [comment]
Does this only occur in Chrome? Does the same problem exist in Firefox? IE? (I dunno even if it runs in IE!)

**Comment by jayrope** [comment]
The Owl runs at 48KHz as a default, so Windows and browser should be congruent. My Mac runs on 44.1KHz. So i have to make sure to loadbang the samplerate~ object to distribute current sample rate to tabread~ etc not to run into pitch problems

**Comment by woldhek** [comment]
This is still open right?

**Comment by diplojocus** [comment]
@woldhek I wasn't able to figure out what's different about it running in Chrome on Windows, doesn't seem to make sense to me. Do you still have this problem?

**Comment by woldhek** [comment]
yeah still the same.

**Comment by diplojocus** [comment]
@woldhek this was a silly one, can you try refreshing your page and see if you still have the same problem? 🤕

**Comment by diplojocus** [comment]
@ntkeep very sorry about the 2 year wait on this :/

It's kinda like how you find your keys in the last place you look. And I can't really say it's due to analogue drift or anything...

Anyway fixed now so you can enjoy perfect pitched pipes everywhere!

**Comment by re-sounding** [comment]
No worries! There was nothing critical about it. Thanks for the fix!
