### ISSUE TITLE
Support [vline~]

### ISSUE THREAD

**Issue by diplojocus** [enzienaudio/heavy#4]

**Comment by olilarkin** [comment]
Yes please :-)

**Comment by diplojocus** [comment]
[vline~] functionality can be replaced by the [hv_vline~] abstraction found in the heavylib 
https://github.com/enzienaudio/heavylib/blob/master/hv_vline%7E.pd

It doesn't have sub-sample accurate enveloping, but you can queue up multiple comma-separated messages.
