### ISSUE TITLE
tabread~ Expecting , delimiter error

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#44]
```
ERROR: Expecting , delimiter: line 33 column 5 (char 516)
```

Caused by this:

```
#N canvas 405 80 237 238 10;
#X obj 64 74 tabread~ blah;
```

**Comment by mhroth** [comment]
Good catch @ylevtov ! This bug would have prevented any patch using `tabread~` from properly compiling, as was due to a (strangely) corrupted object definition file. Thank you!!
