### ISSUE TITLE
Question about API token

### ISSUE THREAD

**Issue by sam-artuso** [enzienaudio/heavy#54]
Hi, I'm using your `uploader.py` in an automated server script that runs as `nobody` user for security reasons.

On Linux, the `nobody` user doesn't have a home directory, so it is not possible to store the token in `~/.heavy/token`.

To work around this issue I hacked your `uploader.py` so that the token can be passed as a command line argument (I can provide a patch, if you are interested).

Reading the source code of `uploader.py` I noticed that under some conditions, the token may be updated:

```
# update the api token, if present
if "token" in reply_json.get("meta",{}) and not args.x:
    if not os.path.exists(os.path.dirname(token_path)):
        os.makedirs(os.path.dirname(token_path)) # ensure that the .heavy directory exists
    with open(token_path, "w") as f:
        f.write(reply_json["meta"]["token"])
    os.chmod(token_path, stat.S_IRUSR | stat.S_IWUSR) # force rw------- permissions on the file
```

I wanted to ask you if and under what conditions this could happen. If it is likely to happen, I may need to make further changes to my code.

My apologies if this is not the right place to ask for support.

**Comment by mhroth** [comment]
The token very rarely changes. There is the opportunity for us to do so, such as in the case of account abuse. At this time, it would be ok even to hardcode it.

I'd love to see your changes as well. Email might be the best option for now (or a `.patch` file, whatever's easier for you). Thank you!
