### ISSUE TITLE
Dollar arguments in top level patch (i.e. _main.pd) crashing uploader

### ISSUE THREAD

**Issue by ylevtov** [enzienaudio/heavy#55]
Not a deal-breaker if you know that this causes a problem already, but a nicer error message would be more friendly for new users.

**Comment by diplojocus** [comment]
Does this still crash?

**Comment by ylevtov** [comment]
Nope

**Comment by ylevtov** [comment]
Fixed

**Comment by diplojocus** [comment]
Thanks!
