### ISSUE TITLE
Destroying patch instance in javascript

### ISSUE THREAD

**Issue by Rjblaauboer** [enzienaudio/heavy#56]
The documentation for vanilla C mentions that new patch instances can be created, processed, and destroyed. But the javascript documentation does not mention whether this is possible in the javascript implementation as well. 

How would I go about this or is this currently not a feature?

**Comment by diplojocus** [comment]
Yes, this is definitely possible, each time you call the constructor it'll create a new instance:

```
heavy = new heavyLib({
  blockSize: 1024,
  sampleRate: webAudioContext.sampleRate,
  printHook: hvPrintHook
});
```

The documentation just gives a simple example with one, but you can create a system to manage multiple patch instances.

p.s. sorry for the delay, not sure why I didnt see this earlier

**Comment by Rjblaauboer** [comment]
No problem, thanks for the reply. How would I go about destroying the instance? Since I didn't see this mentioned in the javascript documentation.

**Comment by diplojocus** [comment]
You can do something like:

```
heavy = new heavyLib({
  blockSize: 1024,
  sampleRate: webAudioContext.sampleRate,
  printHook: hvPrintHook
});
delete heavy;
```

Yes you're right, in the example it'll go out of scope when the tab closes, there's not really an explanation of how to manage multiple instances yet, but it should be fairly straightforward.
