### ISSUE TITLE
support list

### ISSUE THREAD

**Issue by woldhek** [enzienaudio/heavy#61]
i like [c_drunk] from rjlib. would like to include it in heaylib but need [list] objects to do so.

**Comment by diplojocus** [comment]
I've added a refined version of [c_drunk] to heavylib. Does this meant your needs? 

https://github.com/enzienaudio/heavylib/blob/master/hv_drunk.pd

Example here:
https://enzienaudio.com/h/diplojocus/drunk/

**Comment by woldhek** [comment]
i get thsi compile error with that: 1) ←[91mError:←[0m [route bang seed set
seed] in "_main.pd/hv_drunk.pd/router" @
 (x:66, y:92): All arguments to [route] must be unique. Argument "seed" is
repea
ted 2 times.

**Comment by diplojocus** [comment]
Sorry, should be fixed now, just updated heavylib

https://github.com/enzienaudio/heavylib/commit/742b26dc80246de8ee2138a94d0b44855f252f28

**Comment by woldhek** [comment]
confirmed fixed.

**Comment by grrrr** [comment]
Is there a reason that [list] is not implemented? It is essential for all kinds of message processing.

**Comment by mhroth** [comment]
@grrrr It's certain that `list` support will come to Heavy eventually. I'm keen to put together a "Zen of Heavy" list of tips and tricks, and one of the things that it will say is that the thing that Heavy excels at is handling the signal chain. For any functionality that you are supporting with the `list` object, you are probably better off handling it outside of the Heavy context and the sending in more manageable messages.
