### ISSUE TITLE
Undefined reference to alloca with ARM GCC compiler

### ISSUE THREAD

**Issue by pingdynasty** [enzienaudio/heavy#66]
With the new HvUtils.h, `hv_alloca()` is defined as `alloca()`, which would be what you'd expect.

However, with current versions of arm gcc this fails to link with `undefined reference to 'alloca'`.

This works:

```
#if defined __GNUC__
  #define hv_alloca(_n)  __builtin_alloca(_n)
#else
  #define hv_alloca(_n)  alloca(_n)
#endif
```

I'm not sure if this is something you want to change in your HvUtils.h, personally I'm quite happy to keep a local change in place. But recording the problem might be helpful to others.

Ref: https://answers.madewithmarmalade.com/questions/16971/alloca-undefined-in-arm-builds.html

**Comment by mhroth** [comment]
@pingdynasty would `#include <alloca.h>` work for you as well?

**Comment by pingdynasty** [comment]
No it doesn't I'm afraid - note that it's failing to link.
I think it might be a bug in the arm-gcc header files.

**Comment by pingdynasty** [comment]
I lie.
`#include <alloca.h>` works fine!

**Comment by pingdynasty** [comment]
Closing this as resolved.
