### ISSUE TITLE
Support [vcf~]

### ISSUE THREAD

**Issue by diplojocus** [enzienaudio/heavy#7]

**Comment by pingdynasty** [comment]
thx!
I'm having another problem: `Unknown Pd object 'r~'`
I tried changing it to `receive~` but get the same error. Am I missing something?

**Comment by diplojocus** [comment]
It's on the TODO list https://github.com/enzienaudio/heavy/issues/9

**Comment by Simon-L** [comment]
Looking at the objects list, it seems it is supported. Can you confirm [vcf~] is still working?

The following patch, as processed through Heavy, does not produce any sound: (tested the JS and C code)

```
#N canvas 433 184 450 300 10;
#X obj 116 57 phasor~ 440;
#X obj 107 195 dac~;
#X obj 110 143 vcf~ 3;
#X obj 138 85 loadbang;
#X msg 130 113 400;
#X connect 0 0 2 0;
#X connect 2 0 1 0;
#X connect 2 0 1 1;
#X connect 3 0 4 0;
#X connect 4 0 2 1;
```

[bp~] does work though.

**Comment by diplojocus** [comment]
@Simon-L yeah this is a known issue, I've created a separate ticket here: https://github.com/enzienaudio/heavy/issues/113
