### ISSUE TITLE
can't download the wwise plug in

### ISSUE THREAD

**Issue by maxiestudies** [enzienaudio/heavy#71]
when tryin to download the Wwise Win64 plug-in I get this message

Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

**Comment by diplojocus** [comment]
Strange, could you send me a link to your patch?

**Comment by maxiestudies** [comment]
hey Thanks for your answer!
Here is my patch!

https://enzienaudio.com/h/maxiestudies/wwisePlugIn/

2016-02-19 11:46 GMT+01:00 Joe White notifications@github.com:

> Strange, could you send me a link to your patch?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/enzienaudio/heavy/issues/71#issuecomment-186168103.

## 

Maximiliano Estudies
Fixheider Weg 27
51061 Köln
+49 178 36784771
maxiestudies.com
