### ISSUE TITLE
Pd Patch working but Unity Plugin and Compiler Preview is missing parts of patch output

### ISSUE THREAD

**Issue by chrisjdarcy** [enzienaudio/heavy#73]
Compiler is playing ball with the patch, it implements into Unity 5.2.2f1 with no problem, but the plugin isn't outputting everything that is in the patch. Patch plays as it should in Pd but runs into this after compiling. I've downloaded the Pd patch after the compile and there's no problems with, just the Unity plugin. The same goes for the plugin preview.

Patch page here: https://enzienaudio.com/h/Dercii/Water_Movement_Unity_test/

**Comment by diplojocus** [comment]
Hmm it's the bubbles sound that's not playing right? I'll take a look, can you try and isolate the part of the patch that isn't working by itself?

**Comment by chrisjdarcy** [comment]
I'll make a patch solely of the bubble with a gain control and see if it is actually that patch.

**Comment by chrisjdarcy** [comment]
Made the patch, still no output. Is it possible that an object is being overlooked or isn't actually supported?

https://enzienaudio.com/h/Dercii/Bubbles_Test/

**Comment by diplojocus** [comment]
I think there's two issues here:

One is that in Heavy the [vd~] object requires a signal connection to it's inlet. It's an issue in Heavy that we're aiming to fix but for now you need to insert a [sig~] object just before the [vd~] if you're connecting a control object.

The other one that I don't think your patch is doing what you expect it to do. It looks like you're trying to create a single sample delay however, by default in Pd the block size is 64 samples, and the minimum delay you'll be able to set is ~1.45ms. To override this you can use a [block~ 1] object for single sample processing. You'll hear when you add it the output in Pd goes silent, which is what Heavy will do in the javascript implementation.

I would recommend looking at some alternatives to generating your random envelopes. The multiple metros running fast is really going to eat up your CPU. 

Here's a video that shows some patches for doing fire crackle sounds, I think you could re-appropriate them accordingly.

https://www.youtube.com/watch?v=uFOc_53mpBc

**Comment by chrisjdarcy** [comment]
Would it be fine to use [rzero_rev~ 1]-[\* -1] for what I want to do? I had changed it to [vd~] as I thought that was what was causing the output loss.

Would routing the same metro out to multiple sources eat up less resources? Like a master clock, if you will.

**Comment by diplojocus** [comment]
Yeah but additionally, there's another small issue in that the default argument in [rzero_rev~] won't work correctly and you'll have to do something like:

```
|        [sig~ 1]
|         |
[rzero_rev~]
|
```

Sorry that it's not explained anywhere, it's another thing we're looking to fix. It would probably explain why you initially got no output.

> Would routing the same metro out to multiple sources eat up less resources? Like a master clock, if you will.

Yeah that would help a lot.

**Comment by diplojocus** [comment]
ahh if you replace the delayline with [rzero_rev~ 1] i think you need to also replace the [*~ -0.1] afterwards with an [abs~] instead.

**Comment by chrisjdarcy** [comment]
Done as you've suggested. There is output now, but it isn't what is expected.
