### ISSUE TITLE
undefined abstraction arguments cause error

### ISSUE THREAD

**Issue by grrrr** [enzienaudio/heavy#74]
In Pure Data, if a $-argument inside an abstraction is not defined, it defaults to 0. This is often used on purpose, as a way to implement variable length argument lists.
The heavy compiler throws an error if an abstraction argument is not defined.

**Comment by mhroth** [comment]
You are right about that.  Heavy does not support all Pure Data language features. In this case, Heavy expects all arguments to be explicitly specified. For this reason, for example, Heavy will also throw an error if you have a `$1` in the top-level patch. I do not expect this difference to be resolved soon.

**Comment by mhroth** [comment]
We've changed this behavior now. If an argument is not defined it defaults to `0`, as you've suggested.

**Comment by grrrr** [comment]
great, thanks!
