### ISSUE TITLE
[array size] supported?

### ISSUE THREAD

**Issue by grrrr** [enzienaudio/heavy#77]
Hi, using [array size] with a table name in a patch results in a compilation error: "There was an error while connecting two objects. Have all objects been correctly instantiated? Have all inlets and outlets been declared?"
# N canvas 127 367 418 316 10;
# X obj 48 27 adc~;
# X obj 47 262 dac~;
# X obj 168 25 loadbang;
# X obj 288 74 table buffer 100;
# X obj 168 259 send output;
# X obj 169 152 array size buffer;
# X connect 0 0 1 0;
# X connect 2 0 5 0;
# X connect 5 0 4 0;

**Comment by mhroth** [comment]
@grrrr Yes, this is an error on our part. I have fixed it and removed `[array]` from the list of supported objects.

**Comment by grrrr** [comment]
i have to say though that it's a pity that array is not supported

**Comment by mhroth** [comment]
As with many thing in Heavy, "not supported _yet_" :)
