### ISSUE TITLE
Pure data external: #HV_TO_PD sender hook crashes on messages with selector

### ISSUE THREAD

**Issue by grrrr** [enzienaudio/heavy#78]
Sending a message from a heavy patch out to a Pd host is ok for floats, but not for more complex messages involving a selector. The compiled external crashes with a bus error.
Find below an example for a _main.pd where this happens. Float messages sent into the external are converted to messages with a selector - the external crashes immediately on sending the message.
I am suspecting a memory allocation/overrun problem in the sendHook function in the *_tilde.c file.

```
#N canvas 75 215 264 148 10;
#X obj 43 23 adc~;
#X obj 42 71 dac~;
#X obj 124 95 s #HV_TO_PD;
#X obj 124 27 r in;
#X msg 124 65 selector \$1;
#X connect 0 0 1 0;
#X connect 0 1 1 1;
#X connect 3 0 4 0;
#X connect 4 0 2 0;
```

**Comment by grrrr** [comment]
Ok, i got around to taking a look at it. It's a different problem. The generated code doesn't play nicely with the Pure Data API. In Pure Data, symbols must be generated with the `gensym` function, they can't simply be initialized with string pointers (that `hv_msg_getSymbol` delivers).
A diff for the `sendHook` function would look like this, using macros that are defined in m_pd.h:

```
--- _heavy/simplesampler_tilde.ori.c    2016-03-11 23:13:00.000000000 +0100
+++ _heavy/simplesampler_tilde.c        2016-03-11 23:25:36.000000000 +0100
@@ -55,24 +55,16 @@
       } else if (hv_msg_isBang(m, 0)) {
         outlet_bang(outlet);
       } else if (hv_msg_isSymbol(m, 0)) {
-        t_symbol s;
-        s.s_name = hv_msg_getSymbol(m, 0);
-        s.s_thing = NULL;
-        s.s_next = NULL;
-        outlet_symbol(outlet, &s);
+        outlet_symbol(outlet, gensym(hv_msg_getSymbol(m, 0)));
       } else return;
     } else {
       const int argc = hv_msg_getNumElements(m);
       t_atom *argv = (t_atom *) alloca(argc*sizeof(t_atom));
       for (int i = 0; i < argc; i++) {
         if (hv_msg_isFloat(m, i)) {
-          argv[i].a_type = A_FLOAT;
-          argv[i].a_w.w_float = hv_msg_getFloat(m, i);
+          SETFLOAT(argv+i, hv_msg_getFloat(m, i));
         } else if (hv_msg_isSymbol(m, i)) {
-          argv[i].a_type = A_SYMBOL;
-          argv[i].a_w.w_symbol->s_name = hv_msg_getSymbol(m, i);
-          argv[i].a_w.w_symbol->s_thing = NULL;
-          argv[i].a_w.w_symbol->s_next = NULL;
+          SETSYMBOL(argv+i, gensym(hv_msg_getSymbol(m, i)));
         } else return;
       }
       outlet_list(outlet, NULL, argc, argv);
```

**Comment by mhroth** [comment]
@grrrr Thanks for the patch! I've finally had a chance to review it and have merged your patch and pushed the changes to the server. Makes sense!
