### ISSUE TITLE
Heavy's compiler uses a too old version of Wwise

### ISSUE THREAD

**Issue by martinbussyparis** [enzienaudio/heavy#81]
Hi,

I have just realised that Heavy compiles not only the Wwise plugin itself but the runtime part too + the Visual Studio solution, which is great.

Although, having to use an old version of Visual Studio (2013) and Wwise (v2014.1.3) is complicated, especially if I want to copy/paste stuff from old projects. Also, versions of Wwise anterior to 2014.1.4 can't be used with Unity 5 and requires Unity 4, which is an even bigger issue.

Would you mind updating the Heavy compiler to the latest version of Wwise? That would be awesome :)

**Comment by diplojocus** [comment]
@martinbussyparis we're just working on a better solution for v2015/2016 and having an option to have static runtime plugins or dynamic runtime plugins. This is definitely coming soon.

**Comment by martinbussyparis** [comment]
Hey Joe,
What would be a dynamic runtime plugin? Would we be able to live edit the Wwise plugin in PD?
Good to hear about the coming update anyway :)

**Comment by mhroth** [comment]
Heavy now supports Wwise 2016 and later.
