### ISSUE TITLE
[adc~] makes Wwise to crash

### ISSUE THREAD

**Issue by martinbussyparis** [enzienaudio/heavy#82]
![image](https://cloud.githubusercontent.com/assets/11868830/14844549/c0a73cd4-0c60-11e6-863a-34b40ddb9010.png)

The Wwise source plugin version of this patch makes Wwise to crash when the playback starts (tested with Wwise 2014.1.3 and 2015.1.6).

Here is the error report generated by Wwise (including a dump file):
[Wwise_v2015.1.6.Error_Report.2016-04-27.10-20-06.zip](https://github.com/enzienaudio/heavy/files/238121/Wwise_v2015.1.6.Error_Report.2016-04-27.10-20-06.zip)
Here is my PD patch: https://enzienaudio.com/h/martinb/audio_input/

**Comment by mhroth** [comment]
We don't yet support Wwise effects, but it's on the roadmap.

**Comment by martinbussyparis** [comment]
Yes, back then when I tried, I expected [adc~] to work in a source plugin. It was before our discussion about the future support of effect plugins.
Fair enough :)

**Comment by diplojocus** [comment]
Closing this as it should be covered by #85
