### ISSUE TITLE
[send] doesn't seem to work with Wwise source plugins

### ISSUE THREAD

**Issue by martinbussyparis** [enzienaudio/heavy#84]
Issue #13 seems to imply that [send] has been implemented and works within Wwise souce plugins, but I don't see anything in Wwise with this PD patch:
![image](https://cloud.githubusercontent.com/assets/11868830/14845293/e64e097c-0c65-11e6-821c-f6b7423ebaa9.png)
![image](https://cloud.githubusercontent.com/assets/11868830/14845273/d160c392-0c65-11e6-8f2b-35cfe2126474.png)

Is it expected to work? Did I do something wrong?

Patch: https://enzienaudio.com/h/martinb/send/

**Comment by diplojocus** [comment]
ohh sorry @martinbussyparis, yeah this isn't expected to work yet. Changes coming soon that will address expectations like this! But that previous post was more outlining the direction of the API to access hooks in other frameworks like Wwise.

Apologies for any confusion.
