### ISSUE TITLE
Support for [until] ?

### ISSUE THREAD

**Issue by jayrope** [enzienaudio/heavy#86]
Is there a support for [until] in sight? It's very helpful for instance to iterate through tables of audio, when looking for zero crossings.

**Comment by diplojocus** [comment]
@jayrope this has been implemented now and updated on the server
please see: https://enzienaudio.com/docs/pdobjects.html

**Comment by jayrope** [comment]
Very nice! Very quick response, thank a bunch. I will report back, if there is any issues.
