### ISSUE TITLE
Support [throw~], [catch~], [send~] and [receive~]

### ISSUE THREAD

**Issue by diplojocus** [enzienaudio/heavy#9]

**Comment by ghost** [comment]
send and receive are listed on Supported Objects page

**Comment by ghost** [comment]
oh I see, send~ and receive~ are different!

**Comment by diplojocus** [comment]
Yep, you have control rate and signal rate versions. 

Control rate: [s], [send], [r], [receive] - Supported
Signal rate: [s~], [send~], [r~], [receive~] - Not supported

**Comment by diplojocus** [comment]
The following are all supported now:

```
* [s~]
* [send~]
* [r~]
* [receive~]
* [throw~]
* [catch~]
```
