### ISSUE TITLE
Wwise 2016.1?

### ISSUE THREAD

**Issue by GiacomoGaroffolo** [enzienaudio/heavy#96]
I've noticed that in the docs it says Wwise v2016.1 build 5648. Am I missing something? I only see up to 2015.1.7 5584 on audio kinetic website.
Also, any chance to see some Wwise docs for mac users too? Awesome work btw

**Comment by diplojocus** [comment]
@jackverde the new Wwise should be out soon and Mac docs are incoming!

**Comment by GiacomoGaroffolo** [comment]
That means I won't be able to use it till then? I've been trying to get the Dynamic Runtime Plugin to work but no luck

**Comment by diplojocus** [comment]
That's correct, sorry about any confusion. The dynamic plugin is new in 2016 and we're slightly ahead of the curve. Should be released any time now.
