### ISSUE TITLE
hv_vscheduleMessageForReceiver only sends to one receiver

### ISSUE THREAD

**Issue by giuliomoro** [enzienaudio/heavy#98]
If there are multiple receivers with the same name, `hv_vscheduleMessageForReceiver` will only send to one of them (the most recent maybe?).
I am sure there are good reasons for this and I see how it would be good practice, but I would advocate that:
1. it should be documented
2. you should get at the very least a warning, or better an error, at compile time.

**Comment by mhroth** [comment]
Hi @giuliomoro. I've just pushed a fix for this issue. Thanks for pointing it out!
